### CREATE GHOST (Yurei)
POST http://localhost:8081/ws
Content-Type: text/xml

< request/create-yurei.xml

### CREATE GHOST (inline)
POST http://localhost:8081/ws
Content-Type: text/xml

< request/create-poltergeist.xml

### LIST ALL GHOSTS
POST http://localhost:8081/ws
Content-Type: text/xml

< request/list-ghosts.xml

### GET GHOST BY TYPE
POST http://localhost:8081/ws
Content-Type: text/xml
SOAPAction: GetGhost

< request/get-yurei.xml

### GET WSDL
GET http://localhost:8081/ws/ghosts.wsdl
